// let dolar = prompt('Введите сумму в долларах')
// const well = (0.89)
// alert('Сумма в евро'+(well)*(dolar))
// let memory = prompt ('Введите память флешки в ГБ')
// let file = (0.82)
// alert ('На вашу флешку поместится '+( memory)/(file)+' файлов по 820Мб')
// let sum = prompt ('Введите сумму денег в кошельке')
// let choсolate = prompt ('Введите цену шоколадки')
// let change = ((sum)-(Math.trunc((sum)/(choсolate))*(choсolate)))
// alert ('Вы сможете купить '+Math.trunc((sum)/(choсolate)))
// alert ('Cдача '+(change))
// 9. так и не понял как делать
// let number = prompt('Введите число')
// alert (number%2 == 0)
